version: '3.8'

services:
  webrtc-camera:
    build: .
    container_name: webrtc-camera
    restart: unless-stopped
    ports:
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"  # Camera device
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - webrtc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # For Raspberry Pi, limit resources
    mem_limit: 512m
    memswap_limit: 512m
    cpus: '2.0'

networks:
  webrtc-network:
    driver: bridge
